name: CI
on:
  push:
  pull_request:
  merge_group:
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          check_together: 'yes'
          scandir: 'tools'
  swiftformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Cyberbeni/install-swift-tool@v2
        with:
          url: https://github.com/nicklockwood/SwiftFormat
          version: '*' # format: https://devhints.io/semver
      - run: swiftformat --lint OSXCore/ OSX/ GureumTests/ Preferences/ OSXTestApp/
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          project: Gureum.xcodeproj
          scheme: OSX
          sdk: macosx
          destination: platform=macOS
          action: build test
      #- uses: sersoft-gmbh/xcodebuild-action@v1
      #  with:
      #    workspace: Gureum.xcworkspace
      #    scheme: App
      #    sdk: iphonesimulator
      #    destination: platform=iOS Simulator,OS=11.3,name=iPhone X
      #    action: build test
